### PR TITLE
Reorganize the proginfo and use txt templates

### PR DESCRIPTION
**Pull request by carlosedp**

### CODE REVIEW

**Comment by carlosedp** [comment]
What do you think about having a structure like this @cjearls?
Easier to maintain/update?

**Comment by cjearls** [comment]
Yeah, I think this will be good for printing out the programming instructions. Do you think it would be nice to have an option to program the board automatically? It already lists the command that needs to run to program the board, so it might as well automatically program the board as well

**Comment by carlosedp** [comment]
Some Edalize backends support programming the boards via it's `run_main` but almost none implement it since it's dependent on the platform and having local toolchain installed.
I think it's a hassle and easier to have the instructions.

**Comment by cjearls** [comment]
Okay, that's fine, I think it looks good

**Pull request merged**
